"""empty message

Revision ID: e9391616157e
Revises: ff8636a215c0
Create Date: 2022-05-11 21:10:41.006249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9391616157e'
down_revision = 'ff8636a215c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'path')
    # ### end Alembic commands ###
